## src/tests/BUILD

cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/tests/ParentTests:ParentTests",
        "//src/tests/ChildTests:ChildTests",
    ],
)
