## src/tests/ChildTests/BUILD

cc_library(
    name = "ChildTests",
    srcs = ["ChildTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Child:Child",
    ]
)
