## src/tests/ParentTests/BUILD

cc_library(
    name = "ParentTests",
    srcs = ["ParentTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Parent:Parent",
    ]
)
